package pl.visa.dndCM.exception;

public enum ErrorCode {
    USER_NOT_FOUND, AVATAR_NOT_FOUND, RESOURCE_NOT_FOUND, BACKGROUND_NOT_FOUND, SPECIE_NOT_FOUND,
    DND_CLASS_NOT_FOUND,
    USER_ALREADY_EXIST
}
